name: walley
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  get: ^4.6.1
  google_nav_bar: ^5.0.5
  flutter_simple_calculator: ^2.0.0+1
  firebase: ^9.0.2
  firebase_auth: ^3.3.5
  firestore_ui: ^1.22.0
  firebase_core :
  fluttericon: ^2.0.0
  month_year_picker: ^0.1.0+1
  group_button: ^4.2.1
  cloud_firestore: ^3.1.6
  multi_select_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

 
